FROM python:3.8-slim

WORKDIR /usr/src

COPY requirements.txt ./
COPY gevent-23.7.0-cp38-cp38-linux_aarch64.whl .
RUN pip install gevent-23.7.0-cp38-cp38-linux_aarch64.whl
RUN pip install --no-cache-dir -r requirements.txt

VOLUME [ "/usr/src/app/config/", "/usr/src/templates/" ]
COPY . .

CMD [ "python", "-u", "./main.py" ]
