# 天翼云盘配置项

accounts:
  #189cn:
   # - "13602289521@189.cn"
   # - "Gztea@302"

cant_enterFolder:
  # 加载目录时排除的文件夹名，正则 match
  - "同步盘"
  - "我的.."

cant_visFile:
  # 加载目录时排除的文件名，正则 match
  - "\\..*?"

rootPath: "/"
  # 根目录

sys_checkTime: 60
  # 程序自检任务时间间隔（秒，下同）

sys_tokenExpiredTime: 3600
  # token 缓存有效时间

sys_dataExpiredTime: 900
  # 文件目录缓存有效时间

sys_dl_urlExpiredNum: 35
  # 下载链接缓存的有效次数

sys_dl_urlExpiredTime: 300
  # 下载链接缓存的有效时间
