# 开启或停用模块
# true 为开启，false 为停用
OnOff:
  core:
    local: true
      # 本地目录模块
    cloud189: true
      # 天翼云盘模块
    onedrive: true
      # onedrive 模块
    aliyundrive: false
      # 阿里云盘模块
  pre:
    rate_limit.py: true
      # rate limit 预处理，开启后请修改下方相关配置
    verify_referrer.py: false
      # 简单防盗链预处理，开启后请修改下方相关配置
  plugin:
    sys_update.py: false
      # 强制刷新缓存插件

# 预处理安全相关
Security:
  # rate limit 相关设置
  rateLimit:
    maxRequests: 30
      # 一个 timeSecond 内同一 IP 允许的最大请求数

    timeSeconds: 60
      # 时间周期，单位为秒

    allowOrigin:
      # 以下 IP 可无视上述规则
      - 127.0.0.1

    banOrigin:
      # 以下 IP 会被拒绝请求
      - null

  # 防盗链相关设置
  onlyReferrer:
    type: ban
      # 策略类型
      # only: 仅允许 origin 中存在的 referrer
      # ban: 仅阻止 origin 中存在的 referrer

    origin:
      # 以下 Referrer 会被应用至上述规则
      - null
